### ISSUE TITLE
feature: OPEN new TAB instead of FLOAT!

### ISSUE THREAD

**Issue by OmiChrome** [VidocqH/data-viewer.nvim#1]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

sometimes its hard to navigate in float window

### Describe the solution you'd like

Tab as viewer

### Describe alternatives you've considered

idk

**Comment by VidocqH** [comment]
You can now try tab view with this config 😊
```lua
{
  view = { float = false },
}
```

**Comment by OmiChrome** [comment]
Thanks  ☺ 
it was bettter, 
its soo usefull , just need some ⭐ Beautiful ⭐  enhancements to make it look better
